In [1]:
import pandas as pd
import numpy as np      

In [70]:
df = pd.read_csv('train.txt',sep=";", header=None, names=["text","emotion"])

In [74]:
df


text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [73]:
# df.isnull().sum()
df["emotion"].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [39]:
unique_emotions = df["emotion"].unique()
emotions_numbers ={}
i=0
for emo in unique_emotions:
    emotions_numbers[emo] = i
    i+=1
df["emotion"]=df["emotion"].map(emotions_numbers)

In [40]:
df.head()

text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [41]:
df['text'] =df["text"].apply(lambda x :x.lower())


In [42]:
df.head()

text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [43]:
import string
def remove_punc(text):

    return text.translate(str.maketrans('','',string.punctuation))

In [44]:
df['text'] = df['text'].apply(remove_punc)

In [45]:
df

text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [46]:
def remove_number(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new


In [47]:
df['text'] = df['text'].apply(remove_number)


In [48]:
df

text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [49]:
def remove_emoji(txt):
    new = ""
    for i in txt:
        if  i.isascii():
            new = new + i
    return new

In [50]:
df['text'] = df['text'].apply(remove_emoji)

In [51]:
df

text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [52]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import pandas as pd

# 🧠 Run these only once
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')


stop_words = set(stopwords.words('english'))

def remove_stopwords_tokenize(txt):
    if not isinstance(txt, str):
        return txt
    tokens = word_tokenize(txt)
    filtered = [word for word in tokens if word.lower() not in stop_words]
    return ' '.join(filtered)



[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vaibh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vaibh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vaibh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [53]:
df['text'] = df['text'].apply(remove_stopwords_tokenize)


In [54]:
print(df.head())

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1


In [55]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)


In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(x_train)
X_test_bow = bow_vectorizer.transform(x_test)

In [57]:
print(X_train_bow.toarray()) 


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [58]:
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.metrics import accuracy_score
# nb_model = MultinomialNB()
# nb_model.fit(X_train_bow, y_train)
# y_pred = nb_model.predict(X_test_bow)


In [59]:
# accuracy = accuracy_score(y_test, y_pred)
# accuracy

In [60]:
# tfidf_vectorizer = TfidfVectorizer()
# X_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
# X_test_tfidf = tfidf_vectorizer.transform(x_test)

In [61]:
# tfidf_model = MultinomialNB()
# tfidf_model.fit(X_train_tfidf, y_train)
# tfidf_pred = nb_model.predict(X_test_tfidf)

In [62]:
# tfidf_pred

In [63]:
# accurac = accuracy_score(y_test, y_pred)
# accurac

In [64]:
# from sklearn.linear_model import LogisticRegression
# logistic_model = LogisticRegression(max_iter=1000)  
# logistic_model.fit(X_train_tfidf, y_train)
# y_pred_logistic = logistic_model.predict(X_test_tfidf)


In [65]:
# logistic_accuracy = accuracy_score(y_test, y_pred_logistic)
# logistic_accuracy

In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
logistic_model_bow = LogisticRegression(max_iter=1000)
logistic_model_bow.fit(X_train_bow, y_train)
logistic_pred_bow = logistic_model_bow.predict(X_test_bow)


In [67]:
logistic_accuracy_bow = accuracy_score(y_test, logistic_pred_bow)
logistic_accuracy_bow

0.88875

In [68]:
import joblib
joblib.dump(logistic_model_bow, "model.joblib")
joblib.dump(bow_vectorizer, "vectorizer.joblib")


['vectorizer.joblib']